version: "latest"

networks:
  netCapstone:
    external: false

services:
  ChatService:
    container_name: ChatService
    build:
      dockerfile: Dockerfile
    image: chatservice:1
    restart: always
    hostname: chatservice
    ports:
      - "3737:3737"
    networks:
      - netCapstone
