version: "latest"

networks:
  netCapstone:

services:
  CapstoneUserTest:
    container_name: CapstoneUserTest
    image: mongo:latest
    restart: always
    hostname: CapstoneUserTest
    ports:
      - "27019:27017"
    networks:
      - netCapstone

  CAPEurekaRegistry:
    container_name: CAPEurekaRegistry
    image: steeltoeoss/eureka-server:latest
    restart: always
    hostname: CAPEurekaRegistry
    ports:
      - 8761:8761
    networks:
      - netCapstone

  CAPAPIGatewayOcelot:
    container_name: CAPAPIGatewayOcelot
    build:
      context: ./dotnet-apigateway-ocelot
      dockerfile: /Dockerfile
    image: capocelotgatewayapi:1
    restart: always
    hostname: CAPAPIGatewayOcelot
    ports:
      - 5041:80
    networks:
      - netCapstone

  CapstoneDBRedis:
    container_name: CapstoneDBRedis
    image: redis:latest
    restart: always
    hostname: CapstoneDBRedis
    ports:
      - "6379:6379"
    networks:
      - netCapstone

  UserServiceAPI:
    container_name: UserServiceAPI
    build:
      dockerfile: Dockerfile
      context: ./userServiceAPI
    environment:
      - spring.application.name=UserServiceAPI
    image: userserviceapi:1
    restart: always
    hostname: UserServiceAPI
    ports:
      - "8081:8080"
    networks:
      - netCapstone
    depends_on:
      - CapstoneUserTest
      - CAPEurekaRegistry
      - CAPAPIGatewayOcelot

  # ChatService:
  #   container_name: ChatService
  #   build:
  #     context: ./chatservice
  #     dockerfile: Dockerfile
  #   image: chatservice:1
  #   restart: always
  #   hostname: chatservice
  #   ports:
  #     - "8084"
  #   networks:
  #     - netCapstone